blog/urls.py
#!/usr/bin/env python
# coding=utf-8
from django.conf.urls import url
from blog.views import *

app_name = 'blog'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', detail, name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', archives, name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', category, name='category'),
    url(r'^search/$', search, name= 'search'),
]

blogproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
]

comments/urls.py
#!/usr/bin/env python
# coding=utf-8
from django.conf.urls import url
from comments.views import *
app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', post_comment, name='post_comment'),
]

blog/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.utils.six import python_2_unicode_compatible
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length = 100)
    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length = 70)
    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=70)
    body = models.TextField()
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    excerpt = models.CharField(max_length = 200, blank = True)
    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag, blank = True)
    author = models.ForeignKey(User)
    views = models.PositiveIntegerField(default=0)

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-created_time']

blog/views.py
#coding:utf-8
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.http import HttpResponse
from blog.models import *
from django.core.paginator import Paginator,EmptyPage, PageNotAnInteger
from comments.forms import *
from django.db.models import *
from django.views.generic.list import ListView
import markdown

from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
import pygments

class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 3
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        pagination_data = self.pagination_data(paginator, page, is_paginated)

        context.update(pagination_data)
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            return {}
                # 当前页左边连续的页码号，初始值为空
        left = []

        # 当前页右边连续的页码号，初始值为空
        right = []

        # 标示第一页页码后是否需要显示省略号
        left_has_more = False

        # 标示最后一页页码前是否需要显示省略号
        right_has_more = False

        # 标示是否需要显示第一页的页码号。
        # 因为如果当前页左边的连续页码号中已经含有第一页的页码号，此时就无需再显示第一页的页码号
        # 其它情况下第一页的页码是始终需要显示的。
        first = False

        # 标示是否需要显示最后一页的页码号。
        # 需要此指示变量的理由和上面相同。
        last = False

        # 获得用户当前请求的页码号
        page_number = page.number

        # 获得分页后的总页数
        total_pages = paginator.num_pages

        # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
        page_range = paginator.page_range

        if page_number == 1:
            # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）
            # 获取当前页右边的连续页码号。
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]
            # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            right = page_range[page_number:page_number + 2]

            # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
            # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示
            if right[-1] < total_pages - 1:
                right_has_more = True

            # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
            # 所以需要显示最后一页的页码号，通过 last 来指示
            if right[-1] < total_pages:
                last = True

        elif page_number == total_pages:
            # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空）
            # 获取当前页左边的连续页码号。
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
            # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

            # 如果最左边的页码号比第 2 页页码号还大，
            # 说明最左边的页码号和第一页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示
            if left[0] > 2:
                left_has_more = True

            # 如果最左边的页码号比第一页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码
            # 所以需要显示第一页的页码号，通过 first 来指示
            if left[0] > 1:
                first = True
        else:
            # 用户请求的既不是最后一页，也不是第一页，则需要获取当前页左右两边的连续页码号
            # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]

            # 是否需要显示最后一页和最后一页前的省略号
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            # 是否需要显示第一页和第一页后的省略号
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        context = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }

        return context

def search(request):
    q = request.GET.get('q')
    error_msg = ''

    if not q:
        error_msg = '请输入关键词'        
        return render(request, 'blog/index.html', {'error_msg': error_msg})
    post_list = Post.objects.filter(title__icontains=q)
    #post_list = Post.objects.all()
    return render(request, 'blog/index.html', {'error_msg':error_msg, 'post_list': post_list})

def index(request):
    post_list = Post.objects.all().order_by('-created_time')
    paginator = Paginator(post_list, 3)
    page = request.GET.get('page')
    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
        post_list = paginator.page(1)
    except EmptyPage:
        post_list = paginator.page(paginator.num_pages)
    return render(request, 'blog/index.html', context={'post_list': post_list})

def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.increase_views()
    #md = markdown.Markdown(extensions=[
    #                                 'markdown.extensions.extra',
    #                                 'markdown.extensions.codehilite',
    #                                 'markdown.extensions.toc',
    #                              ])
    #form = CommentForm()
    #comment_list = post.comment_set.all()
    #context = {
    #    'post': post,
    #    'form': form,
    #    'comment_list': comment_list
    #}
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        TocExtension(slugify=slugify),
    ])
    post.body = md.convert(post.body)
    form = CommentForm()
    comment_list = post.comment_set.all()
    context = {
        'post': post,
        'toc': md.toc,
        'form': form,
        'comment_list': comment_list        
    }

    return render(request, 'blog/detail.html', context=context)


def archives(request, year, month):
    post_list = Post.objects.filter(created_time__year=year, created_time__month=month)
    return render(request, 'blog/index.html', context={'post_list': post_list})


def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=cate)
    return render(request, 'blog/index.html', context={'post_list': post_list})

templates/blog/base.html
{%load blog_tags%}
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
        {%load staticfiles%}

	    <!-- css -->
        <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css'%}">
		<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
        <link rel="stylesheet" href="{% static 'blog/css/pace.css'%}">
        <link rel="stylesheet" href="{% static 'blog/css/custom.css'%}">
        <link rel="stylesheet" href="{% static 'blog/css/friendly.css' %}">

	    <!-- js -->
        <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
        <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'blog/js/pace.min.js' %}"></script>
        <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
	</head>

	<body>
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
                            <h1><a href="{% url 'blog:index'%}"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
                                    <li class="cl-effect-11"><a href="{%url 'blog:index'%}" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
                                <form role="search" method="get" id="searchform" action="{%url 'blog:search'%}">
                                    {%csrf_token%}
									<input type="search" placeholder="Search" required name="q">
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>
		<div class="copyrights">Collect from <a href="http://www.cssmoban.com/" >网页模板</a></div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-8">
                        {%block main%}
                        {%endblock main%}
					</main>
                    <aside>
                         <!-- 由于 toc 的值为一段 HTML 文本，所以要使用 safe 标签过滤 -->
                        {{ toc|safe  }}
                    </aside>
					<aside class="col-md-4">
						<div class="widget widget-recent-posts">		
							<h3 class="widget-title">Recent Posts</h3>
                            {%get_recent_posts as recent_post_list%}            
							<ul>
                                {%for post in recent_post_list%}
								<li>
                                    <a href="{{post.get_absolute_url}}">{{post.title}}</a>
								</li>
                                {%endfor%}
							</ul>
						</div>
						<div class="widget widget-archives">		
							<h3 class="widget-title">Archives</h3>		
                            {% archives as date_list%}
							<ul>
                                {%for date in date_list%}
								<li>
                                <a href="{% url 'blog:archives' date.year date.month%}">{{date.year}} 年 {{ date.month  }} 月</a>
								</li>
                                {%endfor%}
							</ul>
						</div>

						<div class="widget widget-category">		
							<h3 class="widget-title">Category</h3>
                            {% get_categories as category_list %} 
                            {% get_num_posts as category_list %}
							<ul>
                                {%for category in category_list%}
								<li>
                                <a href="{%url 'blog:category' category.pk%}">{{category.name}}({{category.num_posts}})</a>
								</li>
                                {%endfor%}
                                
							</ul>
						</div>
					</aside>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com -More Templates <a href="http://www.cssmoban.com/" target="_blank" title="模板之家">模板之家</a> - Collect from <a href="http://www.cssmoban.com/" title="网页模板" target="_blank">网页模板</a></p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
                    <li><a href="#">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

        <script src="{% static 'blog/js/script.js' %}"></script>

	</body>
</html>

templates/blog/detail.html
{% extends 'blog/base.html' %}
{%block main%}
<article class="post post-1">
<header class="entry-header">
  <h1 class="entry-title">{{ post.title }}</h1>
  <div class="entry-meta">
    <span class="post-category"><a href="#">{{ post.category.name }} </a></span>

    <span class="post-date">
      <a href="#">
        <time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }} </time>
      </a>
    </span>

    <span class="post-author"><a href="#">{{ post.author }} </a></span>

  </div>
</header>
<div class="entry-content clearfix">
  {{ post.body|safe }}
</div>

<div class="comment-list">
  <h2>评论列表</h2>
  <ul class="list-unstyled">
    {% for comment in comment_list %}
    <li class="comment-item">
      <span class="name">{{ comment.name }}</span>
      <time class="date">{{ comment.created_time }}</time>
      <div class="text">
        {{ comment.text }}
      </div>
    </li>
    {% empty %}
    暂无评论
    {% endfor %}
  </ul>
</div>

<form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
  {% csrf_token %}
  <div class="row">
    <div class="col-md-4">
      <label for="{{ form.name.id_for_label }}">Name:</label>
      {{ form.name }}
      {{ form.name.errors }}
    </div>
    <div class="col-md-4">
      <label for="{{ form.email.id_for_label }}">Email:</label>
      {{ form.email }}
      {{ form.name.errors }}
    </div>
    <div class="col-md-4">
      <label for="{{ form.url.id_for_label }}">Url:</label>
      {{ form.url }}
      {{ form.url.errors }}
    </div>
    <div class="col-md-12">
      <label for="{{ form.text.id_for_label }}">Comment:</label>
      {{ form.text }}
      {{ form.text.errors }}
      <button type="submit"><span>发表</span></button>
    </div>
  </div>    <!-- row -->
</form>
<h2>浏览量: {{post.views}}</h2>
</article>
{%endblock main%}

templates/blog/index.html
{% extends 'blog/base.html' %}
                    {% block main %}
                    {%if error_msg%}
                    <p>{{error_msg}}</p>
                    {%endif%}
                        {%for post in post_list%} 
                        <article class="post post-1">
                            <header class="entry-header">
                               <h1 class="entry-title">
                                   <a href="{{post.get_absolute_url}}">{{post.title}}</a>
                                </h1>
                                <div class="entry-meta">
                                    <span class="post-category">
                                        <a href="#">{{ post.category.name  }} </a>
                                    </span>
    
                                    <span class="post-date">
                                        <a href="#">
                                            <time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}         </time>
                                        </a>
                                    </span>
                                    <span class="post-author"><a href="#">{{ post.author }} </a></span>
    
                                    <span class="comments-link"><a href="#">4 Comments</a></span>
                                </div>
                            </header>
                            <div class="entry-content clearfix">
                                <p>{{ post.body | truncatechars:54  }}</p>
                                <div class="read-more cl-effect-14">    
                                    <a href="{{post.get_absolute_url}}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                                </div>
                            </div>

                        </article>
                        {%empty%}
                        <div class="no-post">暂时还没有发布的文章！</div>
                        {%endfor%}


{% if is_paginated %}
<div class="pagination">
  {% if first %}
    <a href="?page=1">1</a>
  {% endif %}
  {% if left %}
    {% if left_has_more %}
        <span>...</span>
    {% endif %}
    {% for i in left %}
        <a href="?page={{ i }}">{{ i }}</a>
    {% endfor %}
  {% endif %}
  <a href="?page={{ page_obj.number }}" style="color: red">{{ page_obj.number }}</a>
  {% if right %}
    {% for i in right %}
        <a href="?page={{ i }}">{{ i }}</a>
    {% endfor %}
    {% if right_has_more %}
        <span>...</span>
    {% endif %}
  {% endif %}
  {% if last %}
    <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
  {% endif %}
</div>

{% endif %}
                    {% endblock main %}

templates/blog/results.html
{%if error_msg%}
<p>{{error_msg}}</p>
{%endif%}

{%for post in post_list%}
<div>
    在这里显示文章的相应信息
</div>
{% empty %}
    <div class="no-post">
        没有搜索到符合条件的文章
    </div>
{% endfor %}